#!/bin/bash
#Move the files in current directory to other directories acording to their prefix

ADDRESS='/home/gustavolozada/Documents'

for fil in "$(pwd)"/*; do   
    basefil=$(basename "$fil") 
    directory=${basefil%%_*}
    name=${basefil#*_}
    location="$ADDRESS/College/$directory" 
    if [[ -d "$location" ]]; then
         mv $fil "$location/$name"
         echo $name
    elif [[ "$directory" == "Books" ]]; then
	 mv $fil "$ADDRESS/Books/$name"    
         echo $name
    fi
done
