#!/bin/bash
#Shows my list of things to do that are not done (-n)
#Shows my list of things to do that are done (-d)
#Shows all things on the list (-n)

cd ~/Documents/Books/Docs/
readonly with_done=8
readonly without_done=3
readonly done_space=5

full_list () {
    if [[ $last_char == "e" ]]; then #last thing is "Done"
        sub=$length-$with_done
    elif [[ $last_char == "-" ]]; then #last thing is --
        sub=$length-$without_done
    fi
    result=${line:0:$sub}
    echo "$result"
}

done_list () {
    if [[ $last_char == "e" ]]; then #last thing is "Done"
        sub=$length-$with_done
    elif [[ $last_char == "-" ]]; then #last thing is --
        sub=0
    fi
    result=${line:0:$sub}
    echo "$result"
}

not_done_list () {
    if [[ $last_char == "e" ]]; then #last thing is "Done"
        sub=0
    elif [[ $last_char == "-" ]]; then #last thing is --
        sub=$length-$without_done
    fi
    result=${line:0:$sub}
    echo "$result"
}

help () {
    echo " -n         list things not done"
    echo " -d         list things done"
    echo " -f         full list"
    echo " -sd        set following arguments done (by number)"
    echo " -nd        set following arguments undone (if they are done)"
}

set_done () {
    for num in "${@:2}"; do #slices the @ so that it can loop from 2nd arg
        num_length=${#num}
        
        cat ThingsToDo | while read line; do
            list_num=${line:0:num_length}
            length=${#line}
            last_char=${line:$length-1:1} 
            
            if [[ $num == $list_num && $last_char != "e" ]]; then
                replace=$line" Done"
                sed -i "s/$line/$replace/" ThingsToDo
                break
            fi
        done    
    done
}

set_not_done () {
    for num in "${@:2}"; do #slices the @ so that it can loop from 2nd arg
        num_length=${#num}
        
        cat ThingsToDo | while read line; do
            list_num=${line:0:num_length}
            length=${#line}
            last_char=${line:$length-1:1} 
            
            if [[ $num == $list_num && $last_char == "e" ]]; then
                replace=${line:0:$length-$done_space} #takes "Done "
                sed -i "s/$line/$replace/" ThingsToDo
                break
            fi
        done    
    done
}

if [[ $# == 1 ]]; then
    cat ThingsToDo | while read line; do #loop through the file line by line
        first_char=${line:0:1} #parameter:offset:length
        
        length=${#line}
        last_char=${line:$length-1:1} 
        
            case $1 in 
                "-n")
                    substring="$(not_done_list)"
                ;;
                "-d")
                    substring="$(done_list)"
                ;;
                "-f")
                    substring="$(full_list)"
                ;;
                "--help")
                    help
                    break
                ;;
            esac    
            
            if [[ ${#substring} == 0 ]]; then
                continue
            fi
            echo $substring   
    done
elif [[ $# > 1 ]]; then
    case $1 in 
        "-sd")
            set_done $@
        ;;
        "-sn")
            set_not_done $@
        ;;
    esac  
fi  


